// Kompletní katalog opatření přílohy A dle ISO/IEC 27001:2022 (93 opatření).
// České názvy vycházejí z ČSN EN ISO/IEC 27001:2023.

export const CATALOG = [
  // A.5 Organizační opatření (37)
  ['A.5.1', 'Politiky bezpečnosti informací'],
  ['A.5.2', 'Role a odpovědnosti v bezpečnosti informací'],
  ['A.5.3', 'Oddělení povinností'],
  ['A.5.4', 'Odpovědnosti vedení'],
  ['A.5.5', 'Kontakt s orgány veřejné moci'],
  ['A.5.6', 'Kontakt se zájmovými skupinami'],
  ['A.5.7', 'Threat intelligence'],
  ['A.5.8', 'Bezpečnost informací v řízení projektů'],
  ['A.5.9', 'Inventář informací a dalších souvisejících aktiv'],
  ['A.5.10', 'Přípustné použití informací a dalších souvisejících aktiv'],
  ['A.5.11', 'Vrácení aktiv'],
  ['A.5.12', 'Klasifikace informací'],
  ['A.5.13', 'Označování informací'],
  ['A.5.14', 'Přenos informací'],
  ['A.5.15', 'Řízení přístupu'],
  ['A.5.16', 'Správa identit'],
  ['A.5.17', 'Autentizační informace'],
  ['A.5.18', 'Přístupová práva'],
  ['A.5.19', 'Bezpečnost informací v dodavatelských vztazích'],
  ['A.5.20', 'Řešení bezpečnosti informací v dohodách s dodavateli'],
  ['A.5.21', 'Řízení bezpečnosti informací v dodavatelském řetězci ICT'],
  ['A.5.22', 'Monitorování, přezkoumávání a řízení změn služeb dodavatelů'],
  ['A.5.23', 'Bezpečnost cloudových služeb'],
  ['A.5.24', 'Plánování a příprava řízení incidentů bezpečnosti informací'],
  ['A.5.25', 'Posuzování a rozhodování o událostech bezpečnosti informací'],
  ['A.5.26', 'Reakce na incidenty bezpečnosti informací'],
  ['A.5.27', 'Poučení z incidentů bezpečnosti informací'],
  ['A.5.28', 'Sběr důkazů'],
  ['A.5.29', 'Bezpečnost informací při narušení'],
  ['A.5.30', 'Připravenost ICT na kontinuitu činností'],
  ['A.5.31', 'Právní, zákonné, regulační a smluvní požadavky'],
  ['A.5.32', 'Práva duševního vlastnictví'],
  ['A.5.33', 'Ochrana záznamů'],
  ['A.5.34', 'Soukromí a ochrana osobních údajů (PII)'],
  ['A.5.35', 'Nezávislé přezkoumání bezpečnosti informací'],
  ['A.5.36', 'Soulad s politikami, pravidly a normami bezpečnosti informací'],
  ['A.5.37', 'Dokumentované provozní postupy'],
  // A.6 Opatření pro lidské zdroje (8)
  ['A.6.1', 'Prověřování'],
  ['A.6.2', 'Podmínky pracovního vztahu'],
  ['A.6.3', 'Povědomí, vzdělávání a školení'],
  ['A.6.4', 'Disciplinární řízení'],
  ['A.6.5', 'Odpovědnosti po ukončení nebo změně pracovního vztahu'],
  ['A.6.6', 'Dohody o mlčenlivosti'],
  ['A.6.7', 'Práce na dálku'],
  ['A.6.8', 'Hlášení událostí bezpečnosti informací'],
  // A.7 Fyzická bezpečnost (14)
  ['A.7.1', 'Fyzické bezpečnostní perimetry'],
  ['A.7.2', 'Fyzický vstup'],
  ['A.7.3', 'Zabezpečení kanceláří, místností a vybavení'],
  ['A.7.4', 'Monitorování fyzické bezpečnosti'],
  ['A.7.5', 'Ochrana před fyzickými a environmentálními hrozbami'],
  ['A.7.6', 'Práce v zabezpečených oblastech'],
  ['A.7.7', 'Zásada čistého stolu a čisté obrazovky'],
  ['A.7.8', 'Umístění a ochrana zařízení'],
  ['A.7.9', 'Bezpečnost zařízení mimo prostory'],
  ['A.7.10', 'Paměťová média'],
  ['A.7.11', 'Podpůrné služby'],
  ['A.7.12', 'Bezpečnost kabeláže'],
  ['A.7.13', 'Údržba zařízení'],
  ['A.7.14', 'Bezpečná likvidace nebo opětovné použití zařízení'],
  // A.8 Technologická opatření (34)
  ['A.8.1', 'Koncová zařízení uživatelů'],
  ['A.8.2', 'Privilegovaná přístupová práva'],
  ['A.8.3', 'Omezení přístupu k informacím'],
  ['A.8.4', 'Přístup ke zdrojovému kódu'],
  ['A.8.5', 'Bezpečná autentizace'],
  ['A.8.6', 'Řízení kapacit'],
  ['A.8.7', 'Ochrana proti škodlivému softwaru'],
  ['A.8.8', 'Řízení technických zranitelností'],
  ['A.8.9', 'Řízení konfigurace'],
  ['A.8.10', 'Vymazání informací'],
  ['A.8.11', 'Maskování dat'],
  ['A.8.12', 'Prevence úniku dat (DLP)'],
  ['A.8.13', 'Zálohování informací'],
  ['A.8.14', 'Redundance vybavení pro zpracování informací'],
  ['A.8.15', 'Zaznamenávání (logování)'],
  ['A.8.16', 'Monitorovací činnosti'],
  ['A.8.17', 'Synchronizace času'],
  ['A.8.18', 'Použití privilegovaných obslužných programů'],
  ['A.8.19', 'Instalace softwaru na provozní systémy'],
  ['A.8.20', 'Bezpečnost sítí'],
  ['A.8.21', 'Bezpečnost síťových služeb'],
  ['A.8.22', 'Segregace sítí'],
  ['A.8.23', 'Filtrování webového obsahu'],
  ['A.8.24', 'Použití kryptografie'],
  ['A.8.25', 'Životní cyklus bezpečného vývoje'],
  ['A.8.26', 'Požadavky na bezpečnost aplikací'],
  ['A.8.27', 'Bezpečná architektura systémů a inženýrské principy'],
  ['A.8.28', 'Bezpečné programování'],
  ['A.8.29', 'Bezpečnostní testování ve vývoji a akceptaci'],
  ['A.8.30', 'Vývoj zajišťovaný externě'],
  ['A.8.31', 'Oddělení vývojového, testovacího a provozního prostředí'],
  ['A.8.32', 'Řízení změn'],
  ['A.8.33', 'Testovací informace'],
  ['A.8.34', 'Ochrana informačních systémů během auditního testování'],
];
